### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/?last_doc_id=cP7NOVWVxLOzmYO0BmvV
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLWFkc28iLCJhdWQiOiJhcGktYWRzbyIsImF1dGhfdGltZSI6MTc3MjYzMjg4OSwidXNlcl9pZCI6IkllTk00NUVpZ2tXUGg0QTg1RE93eUJtS29sNDIiLCJzdWIiOiJJZU5NNDVFaWdrV1BoNEE4NURPd3lCbUtvbDQyIiwiaWF0IjoxNzcyNjMyODg5LCJleHAiOjE3NzI2MzY0ODksImVtYWlsIjoiYXByZW5kaXozQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhcHJlbmRpejNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.b0KpiSl8YLzL59KTnHoBIb2g0z_EbZLijDIN6CzQdsZeynGSkgx6APAhZ-e8KiewmmBWTqXPj5FdxQOyvjr1samN2jwZ5jKhG440vKgs2bn0OcgFc96P70ArDKk59qsHuoa-Ms_EEFREkta6Jg4G5yC5Yb1StjMhHMR-nG91IYtAcbCt7t8VUWM3emJ18kGRIAZLSBfSCpaTB8BAc9TH2BAKGcsoDuh2xeKab92ICXQrkx4wU_7rSgvwWXCKB6JjxZ8wEpLm2f24skOdtnvF1gfNeJCH5ASAKoJfTWxkILt7X6RvTd5laXtfvFwsy-REDZH-dNNngX6Mbh39leSwGQ
### Crear una nueva tarea (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json

{
    "titulo": "Mi primera tarea API",
    "descripcion": "Probando el desacoplamiento",
    "estado": "Pendiente"
}

### Poner
PUT http://127.0.0.1:8000/api/tareas/J41h5AsHlAeZ43H9EqJ1/
Content-Type: application/json

{
    "titulo": "Mi primer put",
    "descripcion": "Probando el put",
    "estado": "activado"
}

### Borrar

DELETE http://127.0.0.1:8000/api/tareas/u7mdQVTND3gfCgOFqewa/

### Iniciar sesion para obtener el token
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email" : "aprendiz3@gmail.com",
    "rol": "instructor",
    "password" : "123456"
}

### Post de iniciar sesion


POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email" : "aprendiz3@gmail.com",
    "password" : "123456"
}

### 3. Crear una tarea usando el token (POST)

POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJjMjdhZmY1YzlkNGU1MzVkNWRjMmMwNWM1YTE2N2FlMmY1NjgxYzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLWFkc28iLCJhdWQiOiJhcGktYWRzbyIsImF1dGhfdGltZSI6MTc3MjAzNjU1MSwidXNlcl9pZCI6IlhTQjFlYlV3UmpUTkR2SnRRemMydlpqUUFlODMiLCJzdWIiOiJYU0IxZWJVd1JqVE5Edkp0UXpjMnZaalFBZTgzIiwiaWF0IjoxNzcyMDM2NTUxLCJleHAiOjE3NzIwNDAxNTEsImVtYWlsIjoiYXByZW5kaXpAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFwcmVuZGl6QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.PhUwv4P-BDQKKB4KxSz9Rq7BIDAPmPRBZCgY9wFfOcPVjhkT2Mj2Ds93aNu_4HPIyCMYBmR97nTlA-_NfnRi0LMS2Gw5XFqYipHSOG1zpkBmmK02_AvFR2QyYUCYja0FUA5PAD8FB-owqSLoh5vvv_l5S0VKafz89sTStmVdpPjN1FVlPBOOTxoh3_o5EBDBavvhc1mrcwUzQM3yj2rlUp-i8uIfHjTcfiIbxXrO4b9wRtewJwW7pGGWH8ZSmxDtOWqtTKvy6JqRaQFdarKvsvI-3bKpxiqfYf53wbLfYzU6F9J8bjTMNYez3-fqWika4Qxt3Cxw8SjuLZMSipyIhA

{
    "titulo": "Tarea con API segura",
    "descripcion": "Mi primera tarea usando JWT de Firebase",
    "estado": "activado"
}

### 4 subir imagen a firestore
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLWFkc28iLCJhdWQiOiJhcGktYWRzbyIsImF1dGhfdGltZSI6MTc3MjQ2OTIxMCwidXNlcl9pZCI6IkllTk00NUVpZ2tXUGg0QTg1RE93eUJtS29sNDIiLCJzdWIiOiJJZU5NNDVFaWdrV1BoNEE4NURPd3lCbUtvbDQyIiwiaWF0IjoxNzcyNDY5MjEwLCJleHAiOjE3NzI0NzI4MTAsImVtYWlsIjoiYXByZW5kaXozQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhcHJlbmRpejNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.X5FJSLkHx5qLMhMIVUoChyATVSgbH-VZ_veiHdWX8jc-cMfyyEnJWTUQbU6dxUC451awbgj9Ezdt5nXeWyhlKq6oPnromzjgymcYOfuTJCJ-c7mlqdo4qSlSejZTWP4QVDg4hL6iZqE0c9vzRvFKo6HGHUdZFIxk0Y5N9bzgpeqBJkHx1aQkZtl5h6XOTyVaD0j3xyn26-OOjNMKu7SIQOoWxaw7yoN0RuPbGuyoVQjCqeZ8EE-wbwEVQsljERQSbgJcUNTwPRP0WusmT-Ie_DTRgNB7UBhkL5GIo6LQyeKTu715E41zJMENdcqGPk0bbUZ3_3iyxUb9DNKjYLEB-w
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\Users\SENA\Desktop\christian2\donkey.jpeg
--MiBoundary--
